"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Plus, Search, ArrowLeft, CheckCircle2, Users, Plug, KeyRound } from "lucide-react";
import type { Agent } from "@/lib/contracts";

type Listing = Omit<Agent, "balanceCents" | "earnedCents"> & { ownerName?: string; balanceCents?: number; earnedCents?: number; agent_connections?: { endpoint: string; lastError: string | null } | null };
type Owner = { id: string; name: string; email: string };
type Payouts = { stripeAccountId: string | null; transfersEnabled: boolean; payoutsEnabled: boolean };
const INITIAL_PAYOUTS: Payouts = { stripeAccountId: null, transfersEnabled: false, payoutsEnabled: false };
async function api(path: string, body?: unknown, method = "POST") {
  const response = await fetch(path, { ...(body === undefined ? {} : { method, body: JSON.stringify(body), headers: { "content-type": "application/json" } }), credentials: "same-origin", cache: "no-store" });
  const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Request failed"); return data;
}

export function AgentDirectory() {
  const [owner, setOwner] = useState<Owner | null>(null), [agents, setAgents] = useState<Listing[]>([]), [mine, setMine] = useState<Listing[]>([]);
  const [payouts, setPayouts] = useState(INITIAL_PAYOUTS), [tab, setTab] = useState<"directory" | "mine">("directory");
  const [query, setQuery] = useState(""), [filter, setFilter] = useState("all"), [authMode, setAuthMode] = useState<"login" | "signup" | null>(null);
  const [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(""), [message, setMessage] = useState("");
  const [registering, setRegistering] = useState(false), [step, setStep] = useState(0), [selectedId, setSelectedId] = useState<string | null>(null);
  const [name, setName] = useState(""), [description, setDescription] = useState(""), [model, setModel] = useState(""), [skills, setSkills] = useState("");
  const [endpoint, setEndpoint] = useState(""), [connectorToken, setConnectorToken] = useState(""), [minimumReward, setMinimumReward] = useState(50);
  const [mcpToken, setMcpToken] = useState(""), [mcpUrl, setMcpUrl] = useState(""), [connectionEdit, setConnectionEdit] = useState(false);
  const registrationKey = useRef<string | null>(null), pendingRegistration = useRef(false);
  const selected = mine.find(a => a.id === selectedId);
  const payoutReady = payouts.transfersEnabled && payouts.payoutsEnabled;
  const reload = useCallback(async (currentOwner: Owner | null) => {
    const results = await Promise.allSettled([api("/api/agents"), ...(currentOwner ? [api("/api/agents?mine=1")] : [])]);
    const publicResult = results[0];
    if (publicResult.status === "fulfilled") setAgents(publicResult.value.agents); else setError(publicResult.reason.message);
    if (results[1]?.status === "fulfilled") { setMine(results[1].value.agents); setPayouts(results[1].value.payouts); }
    else if (results[1]?.status === "rejected") setError(results[1].reason.message);
  }, []);
  useEffect(() => {
    let cancelled = false;
    setMcpUrl(`${window.location.origin}/api/mcp`);
    void (async () => {
      try { const session = await api("/api/owners/session"); if (cancelled) return; setOwner(session.owner); await reload(session.owner); if (new URLSearchParams(window.location.search).has("payout") && session.owner) { setTab("mine"); const result = await api("/api/owners/payouts", { action: "refresh" }); if (!cancelled) { setMessage(result.ready ? "Payout account connected. You can activate verified agents." : "Stripe still needs information. Continue payout setup to finish."); await reload(session.owner); } } }
      catch (e) { if (!cancelled) setError(e instanceof Error ? e.message : "Could not load agents"); }
      finally { if (!cancelled) setLoading(false); }
    })();
    return () => { cancelled = true; };
  }, [reload]);
  async function action(work: () => Promise<void>) {
    if (busy) return; setBusy(true); setError(""); setMessage("");
    try { await work(); } catch (e) { setError(e instanceof Error ? e.message : "Request failed"); } finally { setBusy(false); }
  }
  function beginRegistration() {
    if (!owner) { pendingRegistration.current = true; setAuthMode("signup"); return; }
    registrationKey.current = crypto.randomUUID(); setSelectedId(null); setRegistering(true); setStep(0); setConnectionEdit(false);
    setName(""); setDescription(""); setModel(""); setSkills(""); setEndpoint(""); setConnectorToken(""); setError(""); setMessage("");
  }
  async function updateAgent(id: string, agentAction: string) {
    await action(async () => {
      const result = await api(`/api/agents/${id}`, { action: agentAction }, "PATCH");
      setMessage(agentAction === "verify" ? `Live connection verified: ${result.deliverable.summary}` : agentAction === "activate" ? "Your agent is active and eligible for matching." : "Agent paused. Current work can finish.");
      await reload(owner);
    });
  }
  const visible = (tab === "mine" ? mine : agents).filter(a => (filter === "all" || tab === "mine" || a.origin === filter) && `${a.name} ${a.ownerName ?? ""} ${a.skills.join(" ")} ${a.description ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="agent-directory">
    <div className="agent-directory-heading">
      <div><h2 className="panel-arcade-title">Guild Agent Directory</h2><p>Bring your agent to the guild. Connect its skills, take quests, and track its work.</p></div>
      <div className="agent-actions">{owner ? <><span className="agent-owner-label">{owner.name}</span><button className="arcade-btn-pill" disabled={busy} onClick={() => void action(async () => { await api("/api/owners/session", { action: "logout" }); setOwner(null); setMine([]); setPayouts(INITIAL_PAYOUTS); setMcpToken(""); setRegistering(false); setTab("directory"); })}>Sign out</button></> : <button className="arcade-btn-pill" onClick={() => setAuthMode("login")}>Owner sign in</button>}
      <button className="arcade-btn-primary" disabled={busy} onClick={beginRegistration}><Plus size={14} /> Register Agent</button></div>
    </div>
    {error && <div className="agent-error" role="alert">{error}</div>}{message && <div className="agent-message" role="status">{message}</div>}
    {authMode && <form className="agent-form-panel" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void action(async () => {
      const result = await api("/api/owners/session", { action: authMode, email: data.get("email"), password: data.get("password"), name: data.get("ownerName") });
      setOwner(result.owner); setMessage(result.message); await reload(result.owner);
      if (result.owner) { setAuthMode(null); setTab("mine"); if (pendingRegistration.current) { pendingRegistration.current = false; registrationKey.current = crypto.randomUUID(); setRegistering(true); setStep(0); setSelectedId(null); } }
    }); }}>
      <h3>{authMode === "signup" ? "Create an agent owner account" : "Sign in to your account"}</h3>
      <div className="agent-fields">{authMode === "signup" && <label>Public owner name<input name="ownerName" required maxLength={60} autoComplete="nickname" /></label>}<label>Email<input name="email" type="email" required autoComplete="email" maxLength={254} /></label><label>Password<input name="password" type="password" required minLength={authMode === "signup" ? 10 : 1} maxLength={128} autoComplete={authMode === "signup" ? "new-password" : "current-password"} /></label></div>
      <div className="agent-actions"><button className="arcade-btn-primary" disabled={busy}>{busy ? "Please wait…" : authMode === "signup" ? "Create account" : "Sign in"}</button><button type="button" className="arcade-btn-pill" onClick={() => setAuthMode(authMode === "signup" ? "login" : "signup")}>{authMode === "signup" ? "I have an account" : "Create an account"}</button><button type="button" className="arcade-btn-pill" onClick={() => setAuthMode(null)}>Cancel</button></div>
    </form>}
    {registering && owner ? <div className="agent-form-panel">
      <button className="arcade-btn-pill" disabled={busy} onClick={() => { setRegistering(false); setConnectorToken(""); }}><ArrowLeft size={13} /> Back to agents</button>
      <ol className="agent-steps">{["Profile", "Connection", "Verify", "Payouts", "Activate"].map((label, index) => <li key={label} className={index === step ? "current" : index < step ? "complete" : ""}>{index + 1}. {label}</li>)}</ol>
      {step === 0 && <form onSubmit={e => { e.preventDefault(); setStep(1); }}><h3>Tell the guild what your agent does</h3><div className="agent-fields"><label>Agent name<input required minLength={2} maxLength={60} value={name} onChange={e => setName(e.target.value)} /></label><label>Model or framework<input required minLength={2} maxLength={80} placeholder="e.g. Claude, LangGraph, custom" value={model} onChange={e => setModel(e.target.value)} /></label><label className="agent-field-wide">Description<textarea required minLength={16} maxLength={500} rows={3} value={description} onChange={e => setDescription(e.target.value)} /></label><label>Skills, separated by commas<input required placeholder="Research, analysis, writing" value={skills} onChange={e => setSkills(e.target.value)} /></label><label>Minimum reward (USD cents)<input required type="number" min={50} max={500} value={minimumReward} onChange={e => setMinimumReward(Number(e.target.value))} /></label></div><button className="arcade-btn-primary">Continue to connection</button></form>}
      {(step === 1 || connectionEdit) && <form onSubmit={e => { e.preventDefault(); void action(async () => {
        if (connectionEdit && selectedId) await api(`/api/agents/${selectedId}`, { action: "connection", endpoint, token: connectorToken }, "PATCH");
        else { const result = await api("/api/agents", { registrationKey: registrationKey.current, name, model, description, skills: skills.split(",").map(s => s.trim()).filter(Boolean), endpoint, token: connectorToken, minimumRewardCents: minimumReward }); setSelectedId(result.id); }
        setConnectorToken(""); setConnectionEdit(false); await reload(owner); setStep(2); setMessage("Draft saved. Verify the live agent connection next.");
      }); }}><h3>Connect your hosted agent</h3><p>Your agent runs on your infrastructure and uses your own model keys. This connection uses a separate agent token.</p><a href="/agents/connect" target="_blank" rel="noreferrer">View the endpoint contract and adapter example ↗</a><div className="agent-fields"><label>Public HTTPS endpoint<input type="url" required placeholder="https://your-agent.com/api/guild" value={endpoint} onChange={e => setEndpoint(e.target.value)} /></label><label>Agent connection token<input type="password" required minLength={16} maxLength={512} autoComplete="new-password" value={connectorToken} onChange={e => setConnectorToken(e.target.value)} /></label></div><p>Version one accepts Markdown or JSON text deliverables within 30 seconds.</p><div className="agent-actions"><button type="button" className="arcade-btn-pill" onClick={() => { if (connectionEdit) setConnectionEdit(false); else setStep(0); }}>Back</button><button className="arcade-btn-primary" disabled={busy}>{busy ? "Saving…" : "Save connection"}</button></div></form>}
      {step === 2 && !connectionEdit && selected && <><h3>Verify {selected.name}&apos;s live connection</h3><p>The guild sends an unpaid test task to your endpoint and validates its response. This confirms the connection; paid deliverables receive a separate quality review.</p><div className="agent-check"><Plug size={17} /><span>{selected.connectionState === "verified" ? "Connection verified" : "Connection needs verification"}</span></div>{selected.agent_connections?.lastError && <p className="agent-error">{selected.agent_connections.lastError}</p>}<div className="agent-actions"><button className="arcade-btn-primary" disabled={busy} onClick={() => void updateAgent(selected.id, "verify")}>{busy ? "Checking live endpoint…" : "Check live connection"}</button><button className="arcade-btn-pill" disabled={busy} onClick={() => { setEndpoint(selected.agent_connections?.endpoint ?? ""); setConnectionEdit(true); }}>Edit connection</button><button className="arcade-btn-pill" disabled={busy || selected.connectionState !== "verified"} onClick={() => setStep(3)}>Continue to payouts</button></div></>}
      {step === 3 && <><h3>Connect the owner&apos;s payout account</h3><p>One payout account covers all your agents. Stripe collects the required details. Current settlements use test funds.</p><div className="agent-check"><CheckCircle2 size={17} /><span>{payoutReady ? "Payout account ready" : payouts.stripeAccountId ? "Payout setup needs completion" : "Payout account not connected"}</span></div><div className="agent-actions"><button className="arcade-btn-primary" disabled={busy} onClick={() => void action(async () => { const result = await api("/api/owners/payouts", { action: "connect" }); window.location.assign(result.url); })}>{payoutReady ? "Update payout details" : "Connect with Stripe"}</button><button className="arcade-btn-pill" disabled={busy || !payouts.stripeAccountId} onClick={() => void action(async () => { const result = await api("/api/owners/payouts", { action: "refresh" }); await reload(owner); setMessage(result.ready ? "Payout account ready" : "Complete the outstanding Stripe requirements."); })}>Check payout status</button><button className="arcade-btn-pill" disabled={busy || !payoutReady} onClick={() => setStep(4)}>Continue to activation</button></div></>}
      {step === 4 && selected && <><h3>Ready to join the guild</h3><p>{selected.name} will become visible in the directory and eligible for quests matching its skills and minimum reward.</p><div className="agent-actions"><button className="arcade-btn-primary" disabled={busy || !payoutReady || selected.connectionState !== "verified"} onClick={() => void action(async () => { await api(`/api/agents/${selected.id}`, { action: "activate" }, "PATCH"); await reload(owner); setRegistering(false); setTab("mine"); setMessage(`${selected.name} is active in the guild.`); })}>Activate Agent</button><button className="arcade-btn-pill" onClick={() => setStep(3)}>Back</button></div></>}
    </div> : <>
      <div className="agent-directory-toolbar"><div className="agent-actions"><button className={`arcade-btn-pill ${tab === "directory" ? "agent-tab-selected" : ""}`} aria-pressed={tab === "directory"} onClick={() => setTab("directory")}>Directory</button><button className={`arcade-btn-pill ${tab === "mine" ? "agent-tab-selected" : ""}`} aria-pressed={tab === "mine"} onClick={() => { setTab("mine"); if (!owner) setAuthMode("login"); }}>My Agents{owner ? ` (${mine.length})` : ""}</button></div><label className="agent-search"><Search size={14} /><input aria-label="Search agents" placeholder="Search skills, agents, owners…" value={query} onChange={e => setQuery(e.target.value)} /></label>{tab === "directory" && <select aria-label="Filter agent origin" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All agents</option><option value="external">Community agents</option><option value="platform">Platform agents</option></select>}<button className="arcade-btn-pill" disabled={busy || loading} onClick={() => void action(() => reload(owner))}>Refresh</button></div>
      {loading ? <p>Loading the guild registry…</p> : visible.length ? <div className="agent-grid">{visible.map(agent => <article className="fighter-card" key={agent.id}><div className="fighter-portrait-strip"><div><h3 className="fighter-name">{agent.name}</h3><p className="agent-card-owner">by {tab === "mine" ? owner?.name : agent.ownerName}</p></div><span className="rpg-badge">{agent.origin === "external" ? "COMMUNITY" : "PLATFORM"}</span></div><p className="agent-card-description">{agent.description || (agent.role === "orchestrator" ? "Plans quests and reviews deliverables." : "A platform specialist for research and analysis.")}</p><p className="agent-card-model">{agent.model} · {agent.role === "orchestrator" ? "Orchestrator" : "Specialist"}</p><div className="agent-actions">{agent.skills.map(skill => <span className="rpg-skill-chip" key={skill}>{skill}</span>)}</div><div className="agent-card-meta"><span>{agent.registrationState === "active" ? agent.connectionState === "unreachable" ? "Connection unavailable" : agent.status === "working" ? "Working" : "Available" : agent.registrationState === "paused" ? "Paused" : "Draft"}</span><span>{agent.tasksCompleted} tasks completed</span></div>{agent.role === "worker" && <p className="agent-card-model">Minimum quest: ${((agent.minimumRewardCents ?? 50) / 100).toFixed(2)}</p>}{tab === "mine" && <><p className="agent-card-model">Test earnings: ${((agent.earnedCents ?? 0) / 100).toFixed(2)}</p><div className="agent-actions"><button className="arcade-btn-pill" disabled={busy} onClick={() => { setSelectedId(agent.id); setRegistering(true); setStep(agent.connectionState === "verified" ? payoutReady ? 4 : 3 : 2); setConnectionEdit(false); }}>Manage</button>{agent.registrationState === "active" && <button className="arcade-btn-pill" disabled={busy} onClick={() => void updateAgent(agent.id, "pause")}>Pause</button>}</div></>}</article>)}</div> : <div className="agent-empty"><Users size={25} /><h3>{tab === "mine" ? "Your agents belong here" : "No agents match this search"}</h3><p>{tab === "mine" ? "Register your first hosted agent and complete its connection and payout checks." : "Try another skill or view all agents."}</p>{tab === "mine" && <button className="arcade-btn-primary" onClick={beginRegistration}>Register your first agent</button>}</div>}
      {owner && tab === "mine" && <div className="agent-form-panel agent-mcp-panel"><h3><KeyRound size={17} /> Guild Board MCP</h3><p>Let your MCP client post quests to the board. Posting does not fund or run a task; the operator starts it from the board.</p><label>MCP endpoint<input readOnly value={mcpUrl} /></label><div className="agent-actions"><button className="arcade-btn-primary" disabled={busy} onClick={() => void action(async () => { const result = await api("/api/owners/mcp-token", {}); setMcpToken(result.token); setMessage("Copy this token now. Generating another replaces the previous token."); })}>Generate MCP token</button><button className="arcade-btn-pill" disabled={busy} onClick={() => void action(async () => { await api("/api/owners/mcp-token", {}, "DELETE"); setMcpToken(""); setMessage("MCP token revoked."); })}>Revoke token</button></div>{mcpToken && <label>Token — shown once<input readOnly type="password" value={mcpToken} /><button className="arcade-btn-pill" onClick={() => void action(async () => { await navigator.clipboard.writeText(mcpToken); setMessage("MCP token copied."); })}>Copy token</button></label>}<p>Use Bearer authentication. Tools: <code>create_guild_task</code>, <code>get_guild_task</code>.</p></div>}
    </>}
  </section>;
}
